<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W2K12-97" name="Freestor TestSuit" tests="3" failures="1" timestamp="24 May 2017 22:21:53 GMT" time="26.078" errors="0">
  <testcase name="correctLogin" time="3.092" classname="StartUp.Login"/>
  <testcase name="inCorrectLogin" time="0.672" classname="StartUp.Login"/>
  <testcase name="wrongDomain" time="1.795" classname="StartUp.Login">
    <failure type="java.lang.AssertionError" message="expected [Login failed. The customer domain does not exist.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Login failed. The customer domain does not exist.] but found []
	at StartUp.Login.wrongDomain(Login.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- wrongDomain -->
</testsuite> <!-- Freestor TestSuit -->
